# Generated by Django 5.2.4 on 2025-07-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem_url', models.URLField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especificacoes', models.TextField(blank=True)),
                ('Categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='rexapp.categoria')),
                ('Fabricante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricante', to='rexapp.fabricante')),
            ],
        ),
    ]
