# Generated by Django 5.2.7 on 2025-10-20 20:37

import django.db.models.deletion
import rexapp.models.Produto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_url', models.ImageField(blank=True, upload_to=rexapp.models.Produto.rename_image)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='imagens', to='rexapp.produto')),
            ],
        ),
    ]
