# Generated by Django 4.2.7 on 2025-09-21 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0002_alter_produto_imagem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Categoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoria', to='rexapp.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Fabricante_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fabricante', to='rexapp.fabricante'),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('Produto_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fabricante', to='rexapp.produto')),
            ],
        ),
    ]
