# Generated by Django 5.2.8 on 2025-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0003_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField( max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(null=True, blank=True ),
        ),
    ]
