# Generated by Django 4.2.7 on 2025-09-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0003_alter_produto_categoria_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='Produto_id',
        ),
        migrations.AddField(
            model_name='imagem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='imagens', to='rexapp.produto'),
        ),
    ]
