# Generated by Django 5.2.6 on 2025-09-29 20:45

import rexapp.models.Imagem
import rexapp.models.Produto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0004_remove_imagem_produto_id_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=rexapp.models.Imagem.rename_image),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.ImageField(blank=True, upload_to=rexapp.models.Produto.rename_image),
        ),
    ]
