# Generated by Django 5.2.8 on 2025-11-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
