# Generated by Django 5.2.7 on 2025-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0002_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
