# Generated by Django 5.2.8 on 2025-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0004_usuario_cpf_usuario_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=True, max_length=14, null=True),
        ),
    ]
