# Generated by Django 5.2.8 on 2025-12-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0007_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
