# Generated by Django 6.0 on 2025-12-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0005_rename_produto_id_item_produto_and_more'),
        ('rexapp', '0008_alter_usuario_nascimento'),
    ]

    operations = [
    ]
