# Generated by Django 6.0 on 2025-12-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0009_merge_20251215_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
