# Generated by Django 6.0.1 on 2026-01-13 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0010_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produto', to='rexapp.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
