# Generated by Django 4.2.7 on 2026-01-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0011_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
