# Generated by Django 5.2.8 on 2026-01-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rexapp', '0013_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='processando', max_length=20),
        ),
    ]
